sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: cyq


  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFhdX9VaBNry4Xm7Lz5
    access-key-secret: 44Yj6FH9cjMZEaTroXHQYxFhEmYLlS
    bucket-name: cyq-bucket-20231209

  redis:
    host: localhost
    port: 6379
    auth: cyq
    database: 1

  wechat:
    appid: wxf07d0dfab5503697
    secret: 6c4dc2101740033ab39864a6c986ed2b
    mchid:
    mchSerialNo:
    private-key-file-path:
    api-v3-key:
    we-chat-pay-cert-file-path:
    notify-url:
    refund-notify-url:
